namespace BGL_BT_App.Backend.DTOs;

public record ProposalResponseDto(
    Guid      Id,
    string    State,
    string    Location,
    string    Type,
    string    DealerName,
    int?      VendorId,
    string?   VendorName,
    string    RsmName,
    string    CommandoName,
    string    Month,
    string    Eligibility,
    string?   Remarks,
    decimal   TotalBudget,
    int       TotalLeadTarget,
    int       TotalRetailTarget,
    decimal   Cac,
    decimal   Cpl,
    string    SubmittedBy,
    DateTimeOffset CreatedAt,
    string?   SubmittedByDisplayName,
    string    Status,
    string?   ApproverNote,
    string?   ApprovedBy,
    DateTimeOffset? DecidedAt,
    string?   TokenNumber,
    int       AllowedCac,
    string?   CacWarning,
    List<ActivityResponseDto> Activities
);